import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Interactive comments",
  description: "Generated by create next app",
};

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik", // we’ll use this variable in Tailwind
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.variable}>
      <body className={` `}>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
